### ISSUE TITLE
Integrating with angular issues

### ISSUE THREAD

**Issue by vigneshrajann** [luncheon/svg-drag-select#1]
Hi team, 
How to integrate svg-drag-select in angular. getting this error.

index.d.ts(38, 14): The expected type comes from property 'svg' which is declared here on type 'SvgDragSelectOptions<SVGImageElement | SVGCircleElement | SVGEllipseElement | SVGLineElement | SVGPathElement | SVGPolygonElement | SVGPolylineElement | SVGRectElement | SVGTextElement | SVGUseElement>'

**Comment by luncheon** [comment]
Thank you for trying this package.

svg-drag-select requires `svg` option as SVGSVGElement.  
In Angular, `@ViewChild('mySvg')` can be used.

Following code has worked.

```typescript
import { Component, ElementRef, OnDestroy, ViewChild } from '@angular/core';
import svgDragSelect from 'svg-drag-select';

@Component({
  selector: 'app-root',
  template: `
    <svg #mySvg>
    </svg>
  `
})
export class AppComponent implements OnDestroy {
  cancelDragSelect?: () => void;

  @ViewChild('mySvg')
  set mySvg({ nativeElement }: ElementRef<SVGSVGElement>) {
    if (this.cancelDragSelect) {
      this.cancelDragSelect();
    }

    const { cancel } = svgDragSelect({
      svg: nativeElement,
      onSelectionChange: event => console.log(event.newlySelectedElements)
    });

    this.cancelDragSelect = cancel;
  }

  ngOnDestroy() {
    if (this.cancelDragSelect) {
      this.cancelDragSelect();
    }
  }
}
```
