### ISSUE TITLE
cancel() function

### ISSUE THREAD

**Issue by nusrat45** [luncheon/svg-drag-select#3]
I can't figure out how to use this function cancel() . I need to use it to unbind all drag-select related events.

**Comment by luncheon** [comment]
```js
const { cancel } = svgDragSelect({ ... });
```

Then,

```js
cancel();
```

unbinds drag-select related event listeners.
That's it.

Is there any strange behavior?

**Comment by luncheon** [comment]
Oh, the README doesn't tell you how to call it...
It should be fixed.
